# Generated by Django 5.0.7 on 2024-07-28 16:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='news_title',
            new_name='headline',
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='news_url',
            new_name='url',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
