# Generated by Django 5.0.7 on 2024-07-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_bookmark_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
