# Generated by Django 5.0.7 on 2024-09-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bookmark_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, to='app.bookmark'),
        ),
    ]
