# Generated by Django 5.0.7 on 2026-04-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_bookmark_title_alter_userprofile_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=255)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("url", models.URLField(unique=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("source", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("national", "National"),
                            ("international", "International"),
                            ("sports", "Sports"),
                            ("science", "Science"),
                            ("health", "Health"),
                        ],
                        max_length=30,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-published_at", "-fetched_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="bookmark",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="bookmark",
            name="category",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="collection",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="source",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="digest_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="digest_frequency",
            field=models.CharField(default="daily", max_length=20),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_categories",
            field=models.CharField(
                default="home,national,international,sports,science,health",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_sources",
            field=models.CharField(
                default="NDTV,The Hindu,India Today,News18", max_length=255
            ),
        ),
        migrations.CreateModel(
            name="SourceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=30)),
                ("endpoint", models.URLField()),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="unknown", max_length=20)),
                ("error_message", models.TextField(blank=True)),
                ("article_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["category", "source"],
                "unique_together": {("source", "category")},
            },
        ),
    ]
