# Generated by Codex on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_newsarticle_alter_bookmark_options_bookmark_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_digest_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
